### PR TITLE
some suggestion

### PR DESCRIPTION
**Pull request by gondrongz11**
a few movie in subscene use year in its url
ex: /the-whale and /the-whale-2022
this commit consider the second one by requesting both

drawbacks, 2000ms delay to prevent "too many request"

### CODE REVIEW

**Comment by gondrongz11** [comment]
somehow prettier messed it up, wait for it

**Comment by gondrongz11** [comment]
whitespace messed it up,
just hide it please

**Comment by gondrongz11** [comment]
retry scraping with year if year in subscene do not match,

consider whole season subs, add ep query to the url

**Comment by dexter21767** [comment]
thank you for you time mate.

**Pull request merged**
